const DB_NAME="vinhvideo_offline_db_v1",STORE="videos";const feed=document.getElementById("feed"),empty=document.getElementById("empty"),drawer=document.getElementById("drawer"),fileInput=document.getElementById("fileInput"),folderInput=document.getElementById("folderInput"),libraryList=document.getElementById("libraryList"),storageInfo=document.getElementById("storageInfo");let db=null,videos=[],filtered="all",muted=true,observer=null,objectUrls=new Map();
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains(STORE))d.createObjectStore(STORE,{keyPath:"id"})};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function tx(m="readonly"){return db.transaction(STORE,m).objectStore(STORE)}function all(){return new Promise((res,rej)=>{const r=tx().getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error)})}function put(v){return new Promise((res,rej)=>{const r=tx("readwrite").put(v);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}function del(id){return new Promise((res,rej)=>{const r=tx("readwrite").delete(id);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}function clear(){return new Promise((res,rej)=>{const r=tx("readwrite").clear();r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
function fmt(n){if(!n)return"0 MB";const u=["B","KB","MB","GB"];let i=0;while(n>=1024&&i<u.length-1){n/=1024;i++}return n.toFixed(i?1:0)+" "+u[i]}function toast(msg){const e=document.createElement("div");e.className="toast";e.textContent=msg;document.body.appendChild(e);setTimeout(()=>e.remove(),2200)}function list(){return filtered==="fav"?videos.filter(v=>v.favorite):videos}
async function refresh(){videos=(await all()).sort((a,b)=>(a.order||0)-(b.order||0)||a.createdAt-b.createdAt);renderFeed();renderLibrary();updateStorage()}
async function updateStorage(){const total=videos.reduce((s,v)=>s+(v.size||0),0);let extra="";if(navigator.storage?.estimate){try{const e=await navigator.storage.estimate();extra=` • ${fmt(e.usage)} / ${fmt(e.quota)}`}catch{}}storageInfo.textContent=`${videos.length} video • offline ${fmt(total)}${extra}`}
function url(v){if(objectUrls.has(v.id))return objectUrls.get(v.id);const u=URL.createObjectURL(v.blob);objectUrls.set(v.id,u);return u}
function renderFeed(){const arr=list();empty.style.display=arr.length?"none":"grid";feed.innerHTML="";if(observer)observer.disconnect();arr.forEach((v,i)=>{const p=document.createElement("section");p.className="videoPage";p.dataset.index=i;p.innerHTML=`<video src="${url(v)}" playsinline loop preload="${i<2?"auto":"metadata"}" ${muted?"muted":""}></video><div class="overlay"><h2>${esc(v.title)}</h2><p>${esc(v.source||"Offline")} • ${fmt(v.size)}</p></div><div class="actions"><button class="actionBtn fav ${v.favorite?"active":""}" data-id="${v.id}">♥</button><button class="actionBtn del" data-id="${v.id}">🗑</button></div><div class="progress"><span></span></div>`;const vid=p.querySelector("video"),bar=p.querySelector(".progress span");vid.addEventListener("timeupdate",()=>{if(vid.duration)bar.style.width=vid.currentTime/vid.duration*100+"%"});p.addEventListener("click",e=>{if(e.target.closest("button"))return;vid.paused?vid.play().catch(()=>{}):vid.pause()});p.querySelector(".fav").onclick=()=>fav(v.id);p.querySelector(".del").onclick=()=>remove(v.id);feed.appendChild(p)});observer=new IntersectionObserver(es=>{es.forEach(e=>{const vid=e.target.querySelector("video");if(!vid)return;if(e.isIntersecting&&e.intersectionRatio>.72){document.querySelectorAll("video").forEach(x=>{if(x!==vid)x.pause()});vid.muted=muted;vid.play().catch(()=>{})}else vid.pause()})},{threshold:[0,.72,1]});document.querySelectorAll(".videoPage").forEach(p=>observer.observe(p))}
function renderLibrary(){const arr=list();libraryList.innerHTML=arr.length?"":"<div class='hint'>Chưa có video trong thư viện.</div>";arr.forEach((v,i)=>{const e=document.createElement("div");e.className="item";e.innerHTML=`<div class="thumb">▶</div><div><h3>${esc(v.title)}</h3><p>${fmt(v.size)} • ${new Date(v.createdAt).toLocaleDateString("vi-VN")}</p></div><div class="itemActions"><button class="mini play">Xem</button><button class="mini fav">${v.favorite?"♥":"♡"}</button><button class="mini del">🗑</button></div>`;e.querySelector(".play").onclick=()=>{closeDrawer();scrollTo(i)};e.querySelector(".fav").onclick=()=>fav(v.id);e.querySelector(".del").onclick=()=>remove(v.id);libraryList.appendChild(e)})}
function scrollTo(i){const p=document.querySelectorAll(".videoPage");if(p[i])p[i].scrollIntoView({behavior:"smooth"})}
async function addFiles(files){const arr=Array.from(files||[]).filter(f=>f.type.startsWith("video/"));if(!arr.length){toast("Không tìm thấy video.");return}toast("Đang lưu video offline...");for(const f of arr){await put({id:crypto.randomUUID(),title:f.webkitRelativePath||f.name,blob:f,type:f.type,size:f.size,source:"Điện thoại",favorite:false,createdAt:Date.now(),order:Date.now()+Math.random()})}await refresh();closeDrawer();toast(`Đã lưu ${arr.length} video offline.`)}
async function fav(id){const v=videos.find(x=>x.id===id);if(!v)return;v.favorite=!v.favorite;await put(v);await refresh()}async function remove(id){if(!confirm("Xóa video này khỏi bộ nhớ offline?"))return;await del(id);const u=objectUrls.get(id);if(u)URL.revokeObjectURL(u);objectUrls.delete(id);await refresh()}
function esc(s){return String(s||"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}function openDrawer(){drawer.classList.add("open")}function closeDrawer(){drawer.classList.remove("open")}
function exportList(){const meta=videos.map(({blob,...r})=>r);const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(meta,null,2)],{type:"application/json"}));a.download="vinhvideo-playlist-metadata.json";a.click();toast("Đã export metadata. File video không nằm trong JSON.")}
document.getElementById("menuBtn").onclick=openDrawer;document.getElementById("emptyAddBtn").onclick=openDrawer;document.getElementById("closeBtn").onclick=closeDrawer;drawer.addEventListener("click",e=>{if(e.target===drawer)closeDrawer()});fileInput.onchange=e=>addFiles(e.target.files);folderInput.onchange=e=>addFiles(e.target.files);document.getElementById("muteBtn").onclick=()=>{muted=!muted;document.querySelectorAll("video").forEach(v=>v.muted=muted);document.getElementById("muteBtn").textContent=muted?"🔇":"🔊"};document.getElementById("allBtn").onclick=()=>{filtered="all";document.getElementById("allBtn").classList.add("active");document.getElementById("favBtn").classList.remove("active");renderFeed();renderLibrary()};document.getElementById("favBtn").onclick=()=>{filtered="fav";document.getElementById("favBtn").classList.add("active");document.getElementById("allBtn").classList.remove("active");renderFeed();renderLibrary()};document.getElementById("clearBtn").onclick=async()=>{if(confirm("Xóa toàn bộ video offline?")){await clear();objectUrls.forEach(URL.revokeObjectURL);objectUrls.clear();await refresh();toast("Đã xóa thư viện.")}};document.getElementById("exportBtn").onclick=exportList;window.addEventListener("online",()=>toast("Đã có internet."));window.addEventListener("offline",()=>toast("Đang ở chế độ offline."));
if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js?v=1").catch(()=>{}));(async()=>{db=await openDB();if(navigator.storage?.persist)navigator.storage.persist().catch(()=>{});await refresh()})();